---

- name: Import the public key used by the package management system
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=7F0CEB10 state=present

- name: Add MongoDB repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse' state=present

- name: Install MongoDB
  apt: pkg=mongodb state=latest update_cache=yes
  notify:
  - start mongodb

