- name: deploy script
  raw: |
    cd var/www/{{ appname }}
    export SECRET_KEY_BASE={{ secretkeybase }}
    export DATABASE_URL=ecto://{{ mysqlusername }}:{{ mysqlpassword }}@localhost/{{ proddbname }}
    mix deps.get --only prod
    MIX_ENV=prod mix compile
    npm install --prefix assets
    npm run deploy --prefix ./assets
    mix phx.digest
    MIX_ENV=prod mix ecto.create
    MIX_ENV=prod mix ecto.migrate
    MIX_ENV=prod mix run priv/repo/seeds.exs
    PORT={{ port }} MIX_ENV=prod elixir --erl "-detached" -S mix phx.server



