- name: Ensure sudoers.d is enabled
  lineinfile: dest=/etc/sudoers state=present backup=yes regexp='^#includedir /etc/sudoers.d' line='#includedir /etc/sudoers.d'

- name: Set up password-less sudo for user
  copy: content="%{{ user }} ALL=(ALL) NOPASSWD:ALL" dest="/etc/sudoers.d/{{ user }}" owner=root group=root mode=0440

- name: Create user
  user: name={{ user }} authorization='' state=present group=root shell=/bin/bash