---
 - name: Add the Redis PPA
   apt_repository: repo='ppa:chris-lea/redis-server' update_cache=yes

 - name: Install Redis from PPA
   apt: name=redis-server state=installed

 - name: Start Redis
   service: name=redis-server state=started