- name: install mysql
  apt:
    pkg:
      - mysql-server
      - python-mysqldb
      - php-mysql
    state: present

- name: start mysql service
  service: name={{ item }} state=started enabled=yes
  with_items:
    - mysql

- name: Create a new user for connections
  mysql_user: 
    name={{ mysqlusername }}
    password={{ mysqlpassword }}
    priv='*.*:ALL'
    state=present

  