---
- name: Install PIP
  apt: pkg=python-pip state=installed update_cache=true

- name: Install Python HTTPLib
  pip: name=httplib2 state=present

- name: Install apt-transport-https
  pip: name=apt-transport-https state=present

- name: Add Java (OpenJDK) Repository
  apt_repository: repo='ppa:openjdk-r/ppa' state=present

- name: Install Java (OpenJDK)
  apt: pkg=openjdk-8-jdk state=installed update_cache=yes

- name: Add Elasticsearch Key
  apt_key:
    url: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'

- name: Add Elasticsearch Repository
  apt_repository: repo='deb https://artifacts.elastic.co/packages/5.x/apt stable main' state=present

- name: Install Elasticsearch
  apt: pkg=elasticsearch state=installed update_cache=yes

- name: Init Elasticsearch
  command: update-rc.d elasticsearch defaults 95 10

- name: Enable Elasticsearch (Start on boot)
  service: name=elasticsearch enabled=yes