- name: install Mysql
  apt: pkg={{ item }} state=latest
  with_items:
    - mysql-server
    - ruby-mysql
    - libmysqlclient-dev

- name: install php5-* extensions
  apt: pkg={{ item }} state=latest
  with_items:
    - libapache2-mod-auth-mysql
    - libapache2-mod-php5
